version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./.db:/var/lib/postgresql/data
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - "8000:8000"
    user: "1000"
    volumes:
      - .:/virs
