version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/virs
    ports:
      - "8000:8000"
    depends_on:
      - db
    # environment:
    #   - PYTHONPATH=/virs
    #   - DJANGO_SETTINGS_MODULE=virs
